# Site settings
baseurl = "https://vaneemy.github.io/"
languageCode = "en-us"
title = "Vanessa Emily"
theme = "hugo-universal-theme"
themesDir = "themes/"
defaultContentLanguage = "en"
disqusShortname = "vanemy"
googleAnalytics = "UA-102325967-1"


# Define the number of posts per page
paginate = 5


[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/vaneEmy"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "https://twitter.com/Vane_Emily"
    pre = "<i class='fa fa-2x fa-twitter'></i>"


[params]
    viewMorePostLink = "/blog/"
    author = "Vanessa Emily"
    defaultKeywords = ["Vanessa", "Emily", "Personal", "blog"]
    defaultDescription = "Personal blog of Vanessa Emily"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "violet"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "your@email.com"

    about_us = "<p></p>"
    copyright = "Copyright (c) 2018. Vanessa Emily; all rights reserved"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.jpg"
    latitude = "19.39068"
    longitude = "-99.2837001"

[Permalinks]
    blog = "/post/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs"></p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From my blog"
    subtitle = "I am Vanessa Emily, I love drawing and programming. The main purpose of writing in my blog is to share my experience in technology world, all the things that I am learning  and of course, for practicing my English skills. I hope you can find it interesting and enjoyable to read."
